source 'https://rubygems.org'

gem 'jekyll', '4.0.0'
gem 'jekyll-theme-cloudcannon', :github => 'CloudCannon/jekyll-theme-cloudcannon', :branch => 'master'
# gem 'jekyll-theme-cloudcannon', :path => '../../jekyll-theme'
gem 'jekyll-autoprefixer'
gem 'jekyll-feed', :github => 'CloudCannon/jekyll-feed', :branch => 'master'
