source 'https://rubygems.org'

gem 'jekyll', '3.8.5'
gem 'jekyll-theme-cloudcannon', :github => 'CloudCannon/jekyll-theme-cloudcannon', :branch => 'master'
gem 'jekyll-autoprefixer'
gem 'jekyll-feed', :github => 'CloudCannon/jekyll-feed', :branch => 'master'
